language: android
os:
  - linux
sudo: true
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
addons:
  apt_packages:
    - pandoc
    - lib32asound2
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386
  artifacts:
    paths:
      - $(git ls-files -o | grep app/build/outputs | tr "\n" ":")
before_install:
 - wget -O- https://raw.githubusercontent.com/guillep/Scale/master/setupScale.sh | sudo bash
 - git clone https://github.com/sbragagnolo/android-travis-dependancies.git $HOME/android
 - export ANDROID_NDK_HOME=$HOME/android/android-ndk-r10d
 - cd android/scripts
 - /usr/bin/scale newImage.st
 - /usr/bin/scale linkSources.st
 - /usr/bin/scale generateAndroidMake.st
 - /usr/bin/scale newResourceImage.st
 - cd ../../
 - mv build buildspur
 - mkdir build
 - cd android/scripts
 - /usr/bin/scale linkSources.st
 - /usr/bin/scale generateStackAndroidMake.st
 - /usr/bin/scale newResourceImage.st 
 - cd ../../
  
script:
 - cd buildspur; ./build.sh ; ./package.sh 
 - cd build; ./build.sh ; ./package.sh 

