language: android
os:
  - linux
sudo: true
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
addons:
  apt_packages:
    - pandoc
  artifacts:
    paths:
      - $(git ls-files -o | grep app/build/outputs | tr "\n" ":")
before_install:
 - wget -O- https://raw.githubusercontent.com/guillep/Scale/master/setupScale.sh | sudo bash
 - pwd
 - ls -lsha 
 - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
 - export ANDROID_NDK_HOME=$HOME/android-ndk-root
 - cd android/scripts; scale newImage.st
 - cd android/scripts; scale linkSources.st
 - cd android/scripts; scale generateAndroidMake.st
 - cd android/scripts; scale newResourceImage.st

  
script:
  build/build.sh
  build/package.sh 

