language: android
os:
  - linux
sudo: true
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
addons:
  apt_packages:
    - pandoc
  artifacts:
    paths:
      - $(git ls-files -o | grep app/build/outputs | tr "\n" ":")
before_install:
 - /usr/bin/pharo/pharo /usr/bin/scaleImage/Pharo.image eval "2+2"
 - wget -O- https://raw.githubusercontent.com/guillep/Scale/master/setupScale.sh | sudo bash
 - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
 - export ANDROID_NDK_HOME=$HOME/android-ndk-root
 - cd android/scripts; /usr/bin/scale newImage.st
 - cd android/scripts; /usr/bin/scale linkSources.st
 - cd android/scripts; /usr/bin/scale generateAndroidMake.st
 - cd android/scripts; /usr/bin/scale newResourceImage.st

  
script:
  build/build.sh
  build/package.sh 

